/**
 * Stable error codes. Clients branch on `code`, never on `message`.
 * Each code maps to exactly one HTTP status on the REST surface.
 */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REUSED: 'TOKEN_REUSED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  NOT_A_PARTICIPANT: 'NOT_A_PARTICIPANT',
  ENCRYPTION_REQUIRED: 'ENCRYPTION_REQUIRED',
  PLAINTEXT_NOT_ALLOWED: 'PLAINTEXT_NOT_ALLOWED',
  MESSAGE_IMMUTABLE: 'MESSAGE_IMMUTABLE',
  PREKEYS_EXHAUSTED: 'PREKEYS_EXHAUSTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  TOKEN_REUSED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN: 403,
  NOT_A_PARTICIPANT: 403,
  PLAINTEXT_NOT_ALLOWED: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  USERNAME_TAKEN: 409,
  EMAIL_TAKEN: 409,
  MESSAGE_IMMUTABLE: 409,
  PREKEYS_EXHAUSTED: 410,
  PAYLOAD_TOO_LARGE: 413,
  ENCRYPTION_REQUIRED: 422,
  RATE_LIMITED: 429,
  INTERNAL: 500,
  SERVICE_UNAVAILABLE: 503,
};

export interface ApiError {
  code: ErrorCode;
  message: string;
  /** Field-level details for VALIDATION_ERROR, retry hints for RATE_LIMITED, etc. */
  details?: Record<string, unknown>;
  requestId?: string;
}
